name: Build Artifact Workflow

on:
  workflow_call:

jobs:
  building_artifact:
    runs-on: ubuntu-latest

    steps:
      - name: CHECKOUT REPOSITORY
        uses: actions/checkout@v3

      - name: SET UP JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: MVN CLEAN PACKAGE
        run: mvn clean package

      - name: UPLOAD BUILD ARTIFACT
        uses: actions/upload-artifact@v3.1.0
        with:
          name: github-actions-jar
          path: .
