name: Main Workflow

on:
  pull_request:
    branches: [ 'main', 'develop']
  push:
    branches: [ 'main', 'develop']

jobs:
  test_workflow:
    uses: ./.github/workflows/test_workflow.yml
    secrets: inherit

  artifact_workflow:
    needs: test_workflow
    uses: ./.github/workflows/artifact_workflow.yml
    secrets: inherit