name: Main Workflow

on:
  pull_request:
    branches: [ 'develop', 'main']

jobs:

  test_workflow:
    uses: ./.github/workflows/sub_test_workflow.yml
    secrets: inherit

  artifact_workflow:
    needs: test_workflow
    uses: ./.github/workflows/sub_artifact_workflow.yml
    secrets: inherit

  docker_workflow:
    needs: artifact_workflow
    uses: ./.github/workflows/sub_docker_workflow.yml
    secrets: inherit