name: Main Workflow

on:
  pull_request:
    branches: [ 'main', 'develop']
  push:
    branches: [ 'main', 'develop']

jobs:
  test_workflow:
    uses: ./.github/workflows/test_workflow.yml
    secrets: inherit

  artifact_workflow:
    needs: test_workflow
    uses: ./.github/workflows/artifact_workflow.yml
    secrets: inherit

  docker_workflow:
    needs: artifact_workflow
    uses: ./.github/workflows/docker_workflow.yml
    secrets:
      DOCKER_HUB_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
      DOCKER_HUB_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
      DOCKER_HUB_REPOSITORY: ${{secrets.DOCKER_HUB_REPOSITORY}}