name: Main Workflow

on:
  pull_request:
    branches: [ 'main', 'develop']
  push:
    branches: [ 'main', 'develop']

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: print secret
        run: echo "docker-hub-username -> ${{secrets.DOCKER_HUB_USERNAME}}"

  test_workflow:
    uses: ./.github/workflows/test_workflow.yml
    secrets: inherit

  artifact_workflow:
    needs: test_workflow
    uses: ./.github/workflows/artifact_workflow.yml
    secrets: inherit

  docker_workflow:
    needs: artifact_workflow
    uses: ./.github/workflows/docker_workflow.yml
    secrets: inherit