name: Main Workflow

on:
  pull_request:
    branches: [ 'main', 'develop']
  push:
    branches: [ 'main', 'develop']

jobs:
  test:
    needs: build
    uses: ./.github/workflows/test_workflow.yml
    secrets: inherit
