name: Main Workflow

on:
  pull_request:
    branches: [ 'develop', 'main']
  push:
    branches: [ 'develop', 'main' ]


jobs:

  test_workflow:
    uses: ./.github/workflows/subworkflows/test_workflow.yml
    secrets: inherit

  artifact_workflow:
    needs: test_workflow
    uses: ./.github/workflows/subworkflows/artifact_workflow.yml
    secrets: inherit

  docker_workflow:
    needs: artifact_workflow
    uses: ./.github/workflows/subworkflows/docker_workflow.yml
    secrets: inherit